import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { closeTestDatabase, query } from '../lib/database';
import { accountById, loginAccount, requireAdminAccount, saveTeamPerson, saveTeamUser, teamDirectory, teamUsers, hashPassword, verifyPassword } from '../lib/accounts';
import { issueSession, sessionUser } from '../lib/auth';
import { normalizeCeidg } from '../lib/registries';
import { getCompany, updateCrm, upsertRegistry, CrmConflictError } from '../lib/store';

test('Individual accounts, administrator authorization, immediate session revocation, managed ownership and migration', async () => {
  const directory = mkdtempSync(path.join(tmpdir(), 'crm-accounts-'));
  process.env.CRM_TEST_DB_PATH = path.join(directory, 'test.sqlite');
  process.env.CRM_SESSION_SECRET = 'fixture-session-secret-at-least-32-characters';
  process.env.CRM_PASSWORD = 'fixture-owner-password-only';
  try {
    const fixture = normalizeCeidg({ id: 'account-firm', nazwa: 'Testowa firma', status: 'AKTYWNY', telefon: '123456789' });
    let company = (await upsertRegistry([fixture], 'CEIDG'))[0];
    // Old assignments survive; example names are not seeded.
    company = await updateCrm(company.id, { assignee: 'Osoba historyczna', note: 'Zachowaj notatkę', tags: ['Ważne'], crmRevision: company.crmRevision });
    const owner = (await accountById('owner'))!;
    const oldPeople = await teamDirectory();
    assert.deepEqual(oldPeople.map(person => person.name), ['Osoba historyczna']);
    assert.equal(owner.login, 'admin');
    assert.equal((await sessionUser(issueSession()))?.role, 'admin');
    const anna = await saveTeamPerson(owner, { name: 'Anna', active: true });
    const user = (await saveTeamUser(owner, { login: 'anna', name: 'Anna Nowak', role: 'member', active: true, personId: anna.id, password: 'fixture-anna-password-only' }))!;
    assert.equal((await loginAccount('anna', 'fixture-anna-password-only'))?.id, user.id);
    assert.equal(await loginAccount('anna', 'wrong-password'), null);
    const token = issueSession(Date.now(), user);
    assert.equal((await sessionUser(token))?.person, 'Anna');
    assert.throws(() => requireAdminAccount(user), /tylko dla administratora/);
    await assert.rejects(saveTeamPerson(user, { name: 'Nieuprawniona', active: true }), /tylko dla administratora/);
    await assert.rejects(saveTeamUser(user, { ...user, role: 'admin' }), /tylko dla administratora/);
    await assert.rejects(saveTeamUser(owner, { ...owner, active: false }), /pozostaje aktywne/);
    await assert.rejects(saveTeamUser(owner, { login: 'inna', name: 'Inna', role: 'member', active: true, personId: anna.id, password: 'fixture-other-password' }), /już połączona/);
    assert.ok(!(await teamUsers()).some(entry => 'passwordHash' in entry));
    const stored = (await query('SELECT passwordHash FROM crm_users WHERE id=?', [user.id])).rows[0];
    assert.ok(String(stored.passwordHash).startsWith('scrypt:'));
    assert.ok(!String(stored.passwordHash).includes('fixture-anna'));
    const hash1 = await hashPassword('fixture-same-password'), hash2 = await hashPassword('fixture-same-password');
    assert.notEqual(hash1, hash2); assert.equal(await verifyPassword('fixture-same-password', hash1), true);
    await assert.rejects(hashPassword('short'), /12/);
    await assert.rejects(updateCrm(company.id, { assignee: 'Anna', crmRevision: company.crmRevision }, user), /inna osoba/);
    company = await updateCrm(company.id, { assignee: '', crmRevision: company.crmRevision }, owner);
    await assert.rejects(updateCrm(company.id, { assignee: 'Dowolny tekst', crmRevision: company.crmRevision }, owner), /aktywną osobę/);
    company = await updateCrm(company.id, { assignee: 'Anna', crmRevision: company.crmRevision }, user);
    await assert.rejects(updateCrm(company.id, { assignee: 'Osoba historyczna', crmRevision: company.crmRevision }, user), /do siebie/);
    await saveTeamPerson(owner, { ...anna, name: 'Anna Nowak' });
    const renamed = (await getCompany(company.id))!;
    assert.equal(renamed.assignee, 'Anna Nowak'); assert.equal(renamed.note, 'Zachowaj notatkę'); assert.deepEqual(renamed.tags, ['Ważne']);
    assert.equal((await sessionUser(token))?.person, 'Anna Nowak');
    await assert.rejects(updateCrm(company.id, { note: 'stary szkic', crmRevision: company.crmRevision }, owner), CrmConflictError);
    await assert.rejects(saveTeamPerson(owner, { name: 'anna nowak', active: true }), /już istnieje/);
    await saveTeamPerson(owner, { ...anna, name: 'Anna Nowak', active: false });
    assert.equal((await sessionUser(token))?.person, '');
    assert.equal((await getCompany(company.id))?.assignee, 'Anna Nowak');
    await saveTeamPerson(owner, { ...anna, name: 'Anna Nowak', active: true });
    const blocked = (await saveTeamUser(owner, { ...user, active: false }))!;
    assert.equal(await sessionUser(token), null); assert.equal(await loginAccount('anna', 'fixture-anna-password-only'), null);
    await assert.rejects(saveTeamUser(owner, { ...user, active: true }), /Odśwież panel/);
    const restored = (await saveTeamUser(owner, { ...blocked, active: true }))!;
    const token2 = issueSession(Date.now(), restored);
    const reset = (await saveTeamUser(owner, { ...restored, password: 'fixture-new-password-only' }))!;
    assert.equal(await sessionUser(token2), null);
    assert.equal(await loginAccount('anna', 'fixture-anna-password-only'), null);
    assert.equal((await loginAccount('anna', 'fixture-new-password-only'))?.id, user.id);
    const token3 = issueSession(Date.now(), reset);
    await saveTeamUser(owner, { ...reset, role: 'admin' });
    assert.equal(await sessionUser(token3), null);
    assert.equal(await sessionUser(`${token3}x`), null);
  } finally { closeTestDatabase(); delete process.env.CRM_TEST_DB_PATH; rmSync(directory, { recursive: true, force: true }); }
});
