import type { Company } from "./types";

export const demoCompanies: Company[] = [
  {
    id: "cmp-1",
    name: "Nova Commerce Sp. z o.o.",
    source: "KRS",
    nip: "6762584102",
    regon: "385120991",
    krs: "0000812451",
    city: "Kraków",
    voivodeship: "małopolskie",
    pkdMain: "47.91.Z",
    pkdName: "Sprzedaż detaliczna prowadzona przez domy sprzedaży wysyłkowej lub Internet",
    category: "Handel",
    website: "https://example.com",
    phone: "+48 12 555 12 12",
    email: "biuro@example.com",
    status: "Do kontaktu",
    tags: ["e-commerce", "dobry lead"],
    online: ["Sklep internetowy", "Allegro", "Ceneo"],
    note: "Sprawdzić ofertę dla kanału marketplace."
  },
  {
    id: "cmp-2",
    name: "Meble Beskid Jan Kowalski",
    source: "CEIDG",
    nip: "7342918401",
    regon: "121883011",
    city: "Nowy Sącz",
    voivodeship: "małopolskie",
    pkdMain: "31.09.Z",
    pkdName: "Produkcja pozostałych mebli",
    category: "Produkcja",
    website: "https://example.org",
    phone: "+48 18 444 21 00",
    email: "kontakt@example.org",
    status: "Zainteresowany",
    tags: ["producent", "sklep online"],
    online: ["Sklep internetowy", "Facebook"],
    lastContact: "2026-10-03",
    note: "Prosi o kontakt po południu."
  },
  {
    id: "cmp-3",
    name: "Techpoint Solutions Sp. z o.o.",
    source: "KRS",
    nip: "5252917220",
    regon: "522981701",
    krs: "0000991502",
    city: "Warszawa",
    voivodeship: "mazowieckie",
    pkdMain: "62.01.Z",
    pkdName: "Działalność związana z oprogramowaniem",
    category: "IT, media i komunikacja",
    website: "https://example.net",
    phone: "+48 22 100 20 30",
    email: "hello@example.net",
    status: "Nowy",
    tags: ["B2B"],
    online: ["Strona WWW", "LinkedIn"]
  },
  {
    id: "cmp-4",
    name: "Dom-Projekt Anna Nowak",
    source: "CEIDG",
    nip: "9452037762",
    regon: "356981224",
    city: "Tarnów",
    voivodeship: "małopolskie",
    pkdMain: "43.32.Z",
    pkdName: "Zakładanie stolarki budowlanej",
    category: "Budownictwo",
    phone: "+48 14 600 11 90",
    status: "Do sprawdzenia",
    tags: ["lokalna"],
    online: []
  },
  {
    id: "cmp-5",
    name: "FitMarket Polska Sp. z o.o.",
    source: "KRS",
    nip: "7792514328",
    regon: "389611112",
    krs: "0000904421",
    city: "Poznań",
    voivodeship: "wielkopolskie",
    pkdMain: "47.91.Z",
    pkdName: "Sprzedaż detaliczna prowadzona przez domy sprzedaży wysyłkowej lub Internet",
    category: "Handel",
    website: "https://shop.example.com",
    phone: "+48 61 822 40 01",
    email: "office@example.com",
    status: "Oferta wysłana",
    tags: ["e-commerce", "marketplace"],
    online: ["Shopify", "Amazon", "Allegro"],
    lastContact: "2026-10-04",
    note: "Wysłana oferta; follow-up za 3 dni."
  },
  {
    id: "cmp-6",
    name: "Trans-Mal Usługi Transportowe",
    source: "CEIDG",
    nip: "8733127402",
    regon: "120992883",
    city: "Brzesko",
    voivodeship: "małopolskie",
    pkdMain: "49.41.Z",
    pkdName: "Transport drogowy towarów",
    category: "Transport i logistyka",
    phone: "+48 14 680 22 40",
    status: "Nie zainteresowany",
    tags: ["transport"],
    online: ["Facebook"],
    lastContact: "2026-09-28"
  }
];
